#!/bin/sh

USER=${USER:-yunion}
HOST=${HOST:-yunion-doc}
DIR=/var/www/doc-os/

rm -rf ./public

#EXIT_AFTER_BUILD=1 ./scripts/build.sh && rsync -avz --delete public/ $USER@$HOST:$DIR
hugo && rsync -avz --delete public/ $USER@$HOST:$DIR
